In [1]:
import numpy as np 

In [2]:
from sklearn.datasets import load_iris

In [3]:
#create variable iris
iris = load_iris()

In [4]:
#kind of object return
type(iris)

sklearn.utils.Bunch

In [5]:
#print out attribute
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
# my X feature
X = iris.data

In [8]:
#4 measurments lined up for instance. length width sepal and pedal length and width
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
#grab the labels
y = iris.target

In [10]:
#what we see here is class 0 class 1 and class 2
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
#class 0 -->[1,0,0]
#class 1 -->[0,1,0]
#class 2 -->[0,0,1]


In [14]:
#transform each of these in vector of 3 
from keras.utils import to_categorical

In [15]:
# now i cast it
y = to_categorical(y)

In [16]:
#150 instances and now it has 3 values per label
y.shape

(150, 3)

In [17]:
#now I have setup y
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [18]:
#now i can split up the data to training set and test set
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [28]:
#now we have the 4 components X_train ( training data)
#the X_test (testing features)
#y_train (labels for the training data)
#y_test ( labels for the test data )
#everything is now been shuffled and mixed


In [38]:
#scale and standarized your data its a good idea
from sklearn.preprocessing import MinMaxScaler

In [30]:
#this is just an explaination what MinMaxScaler does is take that list and divide it by the max value wich is 20 
#everything is between zero and 1,because it has been divided by the max value in this case 20
#np.array([5,10,15,20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [39]:
#creating scaler object
scaler_object = MinMaxScaler()

In [40]:
#then i fit it, only to the training data
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [41]:
#scaled version of 
scaled_X_train = scaler_object.transform(X_train)

In [42]:
scaled_X_test = scaler_object.transform(X_test)

In [44]:
#all the values in our training data are between 0 and 1
#scaled_X_train

In [45]:
#now I am building the network with keras
from keras.models import Sequential
from keras.layers import Dense


In [46]:
#adding layers to the model (dense layer)
#adding output layer with 3 neurons i choose softmax
#each particular layer has different parameters 8,8,3 are neurons in each layer
model = Sequential() #creating Sequential model
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax')) # [0.2.,0.3,0.5]
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


Instructions for updating:
Colocations handled automatically by placer.


In [49]:
#asking summary of the model  with mode.summary()
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [50]:
#i sclae the mode data  X an dY train 1 epoch is running through the entire dataset
#verbose how much output of information , i run it now with 150 epochs
#result should be around 90%
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 0s - loss: 1.1297 - acc: 0.0300
Epoch 2/150
 - 0s - loss: 1.1233 - acc: 0.0200
Epoch 3/150
 - 0s - loss: 1.1168 - acc: 0.0300
Epoch 4/150
 - 0s - loss: 1.1105 - acc: 0.0200
Epoch 5/150
 - 0s - loss: 1.1035 - acc: 0.0300
Epoch 6/150
 - 0s - loss: 1.0970 - acc: 0.1100
Epoch 7/150
 - 0s - loss: 1.0915 - acc: 0.2900
Epoch 8/150
 - 0s - loss: 1.0876 - acc: 0.4300
Epoch 9/150
 - 0s - loss: 1.0854 - acc: 0.4700
Epoch 10/150
 - 0s - loss: 1.0838 - acc: 0.5100
Epoch 11/150
 - 0s - loss: 1.0821 - acc: 0.5400
Epoch 12/150
 - 0s - loss: 1.0806 - acc: 0.5500
Epoch 13/150
 - 0s - loss: 1.0790 - acc: 0.5500
Epoch 14/150
 - 0s - loss: 1.0770 - acc: 0.5500
Epoch 15/150
 - 0s - loss: 1.0748 - acc: 0.5300
Epoch 16/150
 - 0s - loss: 1.0718 - acc: 0.4900
Epoch 17/150
 - 0s - loss: 1.0685 - acc: 0.4600
Epoch 18/150
 - 0s - loss: 1.0649 - acc: 0.4900
Epoch 19/150
 - 0s - loss: 1.0598 - acc: 0.5600
Epoch 20/150
 - 0s - loss: 1.0521 - acc: 0.6400
E